apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: allow-swap
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ''
  kubeletConfig:
    failSwapOn: false